services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=inventory
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/shema.sql:/docker-entrypoint-initdb.d/shema.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
