version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/shema.sql:/docker-entrypoint-initdb.d/shema.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=super_secret_key
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=inventory
    depends_on:
      - postgres
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - server
    restart: unless-stopped

volumes:
  pgdata:
